export const MOCK_WEEK_EVENTS = [
  {
    day: 0,
    events: [
      {
        time: "09:00 - 11:00",
        title: "Algoritmi e Strutture Dati",
        location: "Aula B (Varese)",
        professor: "Giunta Mario",
      },
      {
        time: "14:00 - 16:00",
        title: "Basi di Dati",
        location: "Lab Informatica 1 (Varese)",
        professor: "Ferrari Laura",
      },
    ],
  },
  {
    day: 1,
    events: [
      {
        time: "09:00 - 12:00",
        title: "Programmazione Avanzata",
        location: "Aula A (Varese)",
        professor: "Colombo Andrea",
      },
      {
        time: "14:00 - 15:00",
        title: "Sistemi Operativi",
        location: "Videoconferenza Online",
        professor: "Bianchi Paolo",
        isVideo: true,
      },
    ],
  },
  {
    day: 2,
    events: [
      {
        time: "08:30 - 10:30",
        title: "Reti di Calcolatori",
        location: "Aula C (Varese)",
        professor: "Russo Marco",
      },
      {
        time: "11:00 - 13:00",
        title: "Sistemi Operativi",
        location: "Aula C (Varese)",
        professor: "Bianchi Paolo",
      },
      {
        time: "15:00 - 17:00",
        title: "Matematica Discreta",
        location: "Aula D (Varese)",
        professor: "Esposito Giulia",
      },
    ],
  },
  {
    day: 3,
    events: [
      {
        time: "09:00 - 11:00",
        title: "Architettura degli Elaboratori",
        location: "Lab Informatica 2 (Varese)",
        professor: "De Luca Franco",
      },
      {
        time: "14:00 - 16:00",
        title: "Algoritmi e Strutture Dati",
        location: "Aula B (Varese)",
        professor: "Giunta Mario",
      },
    ],
  },
  {
    day: 4,
    events: [
      {
        time: "09:00 - 12:00",
        title: "Ingegneria del Software",
        location: "Aula A (Varese)",
        professor: "Conti Sara",
      },
      {
        time: "14:00 - 15:30",
        title: "Basi di Dati",
        location: "Videoconferenza Online",
        professor: "Ferrari Laura",
        isVideo: true,
      },
    ],
  },
  { day: 5, events: [] },
  { day: 6, events: [] },
];

const july = (
  d: number,
  time: string,
  title: string,
  location: string,
  professor: string,
  isVideo = false,
) => ({
  date: `2026-07-${d.toString().padStart(2, "0")}`,
  day: (new Date(2026, 6, d).getDay() + 6) % 7,
  time,
  title,
  location,
  professor,
  isVideo,
});

export const MOCK_MONTHLY_EVENTS = [
  july(
    1,
    "09:00 - 11:00",
    "Algoritmi e Strutture Dati",
    "Aula B (Varese)",
    "Giunta Mario",
  ),
  july(
    1,
    "14:00 - 16:00",
    "Basi di Dati",
    "Lab Informatica 1 (Varese)",
    "Ferrari Laura",
  ),
  july(
    2,
    "09:00 - 12:00",
    "Programmazione Avanzata",
    "Aula A (Varese)",
    "Colombo Andrea",
  ),
  july(
    3,
    "08:30 - 10:30",
    "Reti di Calcolatori",
    "Aula C (Varese)",
    "Russo Marco",
  ),
  july(
    3,
    "15:00 - 17:00",
    "Matematica Discreta",
    "Aula D (Varese)",
    "Esposito Giulia",
  ),
  july(
    4,
    "09:00 - 11:00",
    "Architettura degli Elaboratori",
    "Lab Informatica 2 (Varese)",
    "De Luca Franco",
  ),

  july(
    7,
    "09:00 - 11:00",
    "Algoritmi e Strutture Dati",
    "Aula B (Varese)",
    "Giunta Mario",
  ),
  july(
    7,
    "14:00 - 16:00",
    "Basi di Dati",
    "Lab Informatica 1 (Varese)",
    "Ferrari Laura",
  ),
  july(
    8,
    "14:00 - 15:00",
    "Sistemi Operativi",
    "Videoconferenza Online",
    "Bianchi Paolo",
    true,
  ),
  july(
    9,
    "11:00 - 13:00",
    "Sistemi Operativi",
    "Aula C (Varese)",
    "Bianchi Paolo",
  ),
  july(
    9,
    "15:00 - 17:00",
    "Matematica Discreta",
    "Aula D (Varese)",
    "Esposito Giulia",
  ),
  july(
    10,
    "14:00 - 16:00",
    "Algoritmi e Strutture Dati",
    "Aula B (Varese)",
    "Giunta Mario",
  ),
  july(
    11,
    "09:00 - 12:00",
    "Ingegneria del Software",
    "Aula A (Varese)",
    "Conti Sara",
  ),
  july(
    11,
    "14:00 - 15:30",
    "Basi di Dati",
    "Videoconferenza Online",
    "Ferrari Laura",
    true,
  ),

  july(
    14,
    "09:00 - 11:00",
    "Reti di Calcolatori",
    "Aula C (Varese)",
    "Russo Marco",
  ),
  july(
    15,
    "09:00 - 12:00",
    "Programmazione Avanzata",
    "Aula A (Varese)",
    "Colombo Andrea",
  ),
  july(
    16,
    "08:30 - 10:30",
    "Architettura degli Elaboratori",
    "Lab Informatica 2 (Varese)",
    "De Luca Franco",
  ),
  july(
    16,
    "11:00 - 13:00",
    "Basi di Dati",
    "Lab Informatica 1 (Varese)",
    "Ferrari Laura",
  ),
  july(
    17,
    "09:00 - 11:00",
    "Algoritmi e Strutture Dati",
    "Aula B (Varese)",
    "Giunta Mario",
  ),
  july(
    18,
    "09:00 - 11:00",
    "Ingegneria del Software",
    "Aula A (Varese)",
    "Conti Sara",
  ),
  july(
    18,
    "14:00 - 16:00",
    "Matematica Discreta",
    "Aula D (Varese)",
    "Esposito Giulia",
  ),

  july(
    21,
    "09:00 - 11:00",
    "Sistemi Operativi",
    "Aula C (Varese)",
    "Bianchi Paolo",
  ),
  july(
    22,
    "14:00 - 15:00",
    "Reti di Calcolatori",
    "Videoconferenza Online",
    "Russo Marco",
    true,
  ),
  july(
    23,
    "09:00 - 12:00",
    "Programmazione Avanzata",
    "Aula A (Varese)",
    "Colombo Andrea",
  ),
  july(
    24,
    "14:00 - 16:00",
    "Algoritmi e Strutture Dati",
    "Aula B (Varese)",
    "Giunta Mario",
  ),
  july(
    25,
    "09:00 - 11:00",
    "Ingegneria del Software",
    "Aula A (Varese)",
    "Conti Sara",
  ),

  july(
    28,
    "09:00 - 11:00",
    "Basi di Dati",
    "Lab Informatica 1 (Varese)",
    "Ferrari Laura",
  ),
  july(
    29,
    "09:00 - 12:00",
    "Sistemi Operativi",
    "Aula C (Varese)",
    "Bianchi Paolo",
  ),
  july(
    30,
    "14:00 - 16:00",
    "Matematica Discreta",
    "Aula D (Varese)",
    "Esposito Giulia",
  ),
  july(
    31,
    "09:00 - 11:00",
    "Algoritmi e Strutture Dati",
    "Aula B (Varese)",
    "Giunta Mario",
  ),
];

export const MOCK_SUBJECTS = [
  "Algoritmi e Strutture Dati",
  "Architettura degli Elaboratori",
  "Basi di Dati",
  "Ingegneria del Software",
  "Matematica Discreta",
  "Programmazione Avanzata",
  "Reti di Calcolatori",
  "Sistemi Operativi",
];
